version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - mysql_db
    restart: always

  mysql_db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=palletes
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3306